### ISSUE TITLE
Add Package to Bower

### ISSUE THREAD

**Issue by eduardo-costa** [netbeast/colorsys#2]
To facilitate the usage on front end development, prepare the project structure to be sent to bower database.

**Comment by jsdario** [comment]
Nice idea, should be available now!

https://github.com/netbeast/colorsys/tree/bower

**Comment by eduardo-costa** [comment]
Nice!
Then what is missing is to register it
http://bower.io/search/?q=colorsys

**Comment by jsdario** [comment]
It is already registered, you can run `bower install colorsys`. However it does not appear on search. Any ideas why? I guess it takes a while, but don't know.

**Comment by eduardo-costa** [comment]
Possibly because there isn't a tag/release with the same bower.json version?

2016-02-13 12:55 GMT-02:00 Jesús Darío notifications@github.com:

> It is already registered, you can run bower install colorsys. However it
> does not appear on search. Any ideas why? I guess it takes a while, but
> don't know.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/netbeast/colorsys/issues/2#issuecomment-183682226.

## 

[image: Imagem inline 1]

**Comment by jsdario** [comment]
http://bower.io/search/?q=colorsys

:+1:
