### ISSUE TITLE
Bug in hsv2Rgb

### ISSUE THREAD

**Issue by ghost** [netbeast/colorsys#6]
When the argument passed to the object it encounters an error.

**Comment by jsdario** [comment]
I cannot reproduce the bug, can you please be more explicit? 
This is what I tried:

```
colorsys.hsv2Rgb({ h: 0 , s: 0 , v: 100 })
{ r: 255, g: 255, b: 255 }
```

**Comment by ghost** [comment]
Bagh version of npm. There is such a tape (and not only in hsv2Rgb):
`colorsys.hsv2Rgb = function (h, s, v) {
if (typeof h === 'object') {
    const args = r
    h = args.h; s = args.s; v = args.v;
  }`

**Comment by jsdario** [comment]
Thanks @Pshoniuk for the hint. I already have republished and added some scripts in **package.json** to make it easier for contributors to update the npm and bower packages.
