### ISSUE TITLE
ColorSys >=1.0.18: Arrow Function

### ISSUE THREAD

**Issue by f-aubert** [netbeast/colorsys#9]
Hello,
I happen to use ColorSys with IE 11, and from version 1.0.18 it contains a single arrow function, as far as I can tell, 'rotateHue'? that causes IE 11 troubles. Is there a reason to use an arrow function there? Could it be rewritten?
Thanks

**Comment by jsdario** [comment]
Hi, thanks for opening an issue!

No, there is not any specific reason. I encourage you to submit a PR changing it :)

**Comment by ashish-kale** [comment]
@jsdario please see PR #10 for this
